# Generated by Django 4.1.2 on 2022-10-28 00:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=2)),
                ('scope', models.CharField(max_length=63)),
                ('status', models.CharField(choices=[('Pre-Construction', 'Pre-Construction'), ('(E) Not Found', '(E) Not Found'), ('No Construction', 'No Construction'), ('Post-Construction', 'Post-Construction'), ('Pending Direction', 'Pending Direction'), ('(E) Capped', '(E) Capped')], default='(E) Not Found', max_length=20)),
                ('pp_history', models.JSONField()),
                ('geometry_type', models.CharField(choices=[('Point', 'Point'), ('MultiLineString', 'MultiLineString'), ('MultiPolygon', 'MultiPolygon')], default='Point', max_length=20)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=2), size=None)),
                ('feature_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.featurecollection')),
            ],
        ),
    ]
