# Generated by Django 4.1.2 on 2022-11-01 23:25

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_feature_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='data',
            field=models.JSONField(default=mainapp.models.empty_dict),
        ),
        migrations.AlterField(
            model_name='feature',
            name='pp_history',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='featurecollection',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='featurecollection',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
